from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField, SelectField, URLField
from wtforms.validators import DataRequired, Email, Length, EqualTo

class LoginForm(FlaskForm):
    email = StringField(label='Email Address', validators=[DataRequired(), Email(message='⚠️ Enter A Valid Email Address!')], render_kw={"placeholder": "Email Address"})
    password = PasswordField(label='Password', validators=[DataRequired(), Length(min=6, max=255,  message='⚠️ Password strength must be between %(min)d and %(max)d characters!')], render_kw={"placeholder": "Password"})
    show_password = BooleanField('Show password', id='check')
    submit = SubmitField(label=('Log In'))

class RegisterForm(FlaskForm):
    username = StringField(label='Username', validators=[DataRequired(), Length(min=3, max=255,  message='⚠️ Username length must be between %(min)d and %(max)d characters!')], render_kw={"placeholder": "Username"})
    email = StringField(label='Email Address', validators=[DataRequired(), Email(message='⚠️ Enter A Valid Email Address!')], render_kw={"placeholder": "Email Address"})
    password = PasswordField(label='Password', validators=[DataRequired(), Length(min=6, max=255,  message='⚠️ Password strength must be between %(min)d and %(max)d characters!')], render_kw={"placeholder": "Password"})
    confirm_password = PasswordField(label='Confirm Password', validators=[DataRequired(), EqualTo('password', message='⚠️ The Passwords Entered Do Not Match!')], render_kw={"placeholder": "Confirm Password"})
    submit = SubmitField(label=('Sign Up'))

class CreatePostForm(FlaskForm):
    title = StringField(label='Title', validators=[DataRequired(), Length(min=3, max=255,  message='⚠️ Title length must be between %(min)d and %(max)d characters!')], render_kw={"placeholder": "Title"})
    description = TextAreaField(label='Description', validators=[DataRequired(), Length(min=3, max=10000,  message='⚠️ Description length must be between %(min)d and %(max)d characters!')], render_kw={"placeholder": "Description", 'rows': 10})
    tags = StringField(label='Tags', validators=[DataRequired(), Length(min=3, max=255,  message='⚠️ Tags length must be between %(min)d and %(max)d characters!')], render_kw={"placeholder": "Tags"})
    submit = SubmitField(label=('Submit'))

class UpdatePostForm(FlaskForm):
    title = StringField(label='Title', validators=[DataRequired(), Length(min=3, max=255,  message='⚠️ Title length must be between %(min)d and %(max)d characters!')], render_kw={"placeholder": "Title"})
    description = TextAreaField(label='Description', validators=[DataRequired(), Length(min=3, max=10000,  message='⚠️ Description length must be between %(min)d and %(max)d characters!')], render_kw={"placeholder": "Description", 'rows': 10})
    bug_status = SelectField(label='Select Status',choices=[
        ('Resolved', 'Resolved'),
        ('In Progress', 'In Progress'),
        ('Unresolved', 'Unresolved')
    ], render_kw={"placeholder": "Choose Status"})
    submit = SubmitField(label=('Submit'))

class AddCommentsForm(FlaskForm):
    comment = TextAreaField(label = 'Comment',validators=[DataRequired(), Length(min=6, max=1000,  message='⚠️ Comment length must be between %(min)d and %(max)d characters!')], render_kw={"placeholder": "Your Comment", 'rows': 5})
    submit= SubmitField('Submit')

class EditCommentsForm(FlaskForm):
    comment = TextAreaField(label = 'Comment',validators=[DataRequired(), Length(min=6, max=1000,  message='⚠️ Comment length must be between %(min)d and %(max)d characters!')], render_kw={"placeholder": "Your Comment", 'rows': 5})
    submit= SubmitField('Submit')

class EditProfileForm(FlaskForm):
    username = StringField(label='Username', validators=[DataRequired(), Length(min=3, max=255,  message='⚠️ Username length must be between %(min)d and %(max)d characters!')], render_kw={"placeholder": "Username"})
    email = StringField(label='Email Address', validators=[DataRequired(), Email(message='⚠️ Enter A Valid Email Address!')], render_kw={"placeholder": "Email Address", 'readonly': True})
    bio = TextAreaField(label='Bio', validators=[DataRequired(), Length(min=3, max=1000,  message='⚠️ Bio length must be between %(min)d and %(max)d characters!')], render_kw={"placeholder": "Bio", 'rows': 10})
    profession = StringField(label='Profession', validators=[DataRequired(), Length(min=3, max=255,  message='⚠️ Name length must be between %(min)d and %(max)d characters!')], render_kw={"placeholder": "Tags"})
    country = SelectField(label='Select Country',choices=[
        ('Afganistan', ('Afghanistan')),
        ('Albania', ('Albania')),
        ('Algeria', ('Algeria')),
        ('American Samoa', ('American Samoa')),
        ('Andorra', ('Andorra')),
        ('Angola', ('Angola')),
        ('Anguilla', ('Anguilla')),
        ('Antigua & Barbuda', ('Antigua & Barbuda')),
        ('Argentina', ('Argentina')),
        ('Armenia', ('Armenia')),
        ('Aruba', ('Aruba')),
        ('Australia', ('Australia')),
        ('Austria', ('Austria')),
        ('Azerbaijan', ('Azerbaijan')),
        ('Bahamas', ('Bahamas')),
        ('Bahrain', ('Bahrain')),
        ('Bangladesh', ('Bangladesh')),
        ('Barbados', ('Barbados')),
        ('Belarus', ('Belarus')),
        ('Belgium', ('Belgium')),
        ('Belize', ('Belize')),
        ('Benin', ('Benin')),
        ('Bermuda', ('Bermuda')),
        ('Bhutan', ('Bhutan')),
        ('Bolivia', ('Bolivia')),
        ('Bonaire', ('Bonaire')),
        ('Bosnia & Herzegovina', ('Bosnia & Herzegovina')),
        ('Botswana', ('Botswana')),
        ('Brazil', ('Brazil')),
        ('British Indian Ocean Ter', ('British Indian Ocean Ter')),
        ('Brunei', ('Brunei')),
        ('Bulgaria', ('Bulgaria')),
        ('Burkina Faso', ('Burkina Faso')),
        ('Burundi', ('Burundi')),
        ('Cambodia', ('Cambodia')),
        ('Cameroon', ('Cameroon')),
        ('Canada', ('Canada')),
        ('Canary Islands', ('Canary Islands')),
        ('Cape Verde', ('Cape Verde')),
        ('Cayman Islands', ('Cayman Islands')),
        ('Central African Republic', ('Central African Republic')),
        ('Chad', ('Chad')),
        ('Channel Islands', ('Channel Islands')),
        ('Chile', ('Chile')),
        ('China', ('China')),
        ('Christmas Island', ('Christmas Island')),
        ('Cocos Island', ('Cocos Island')),
        ('Colombia', ('Colombia')),
        ('Comoros', ('Comoros')),
        ('Congo', ('Congo')),
        ('Cook Islands', ('Cook Islands')),
        ('Costa Rica', ('Costa Rica')),
        ('Cote DIvoire', ('Cote DIvoire')),
        ('Croatia', ('Croatia')),
        ('Cuba', ('Cuba')),
        ('Curaco', ('Curacao')),
        ('Cyprus', ('Cyprus')),
        ('Czech Republic', ('Czech Republic')),
        ('Denmark', ('Denmark')),
        ('Djibouti', ('Djibouti')),
        ('Dominica', ('Dominica')),
        ('Dominican Republic', ('Dominican Republic')),
        ('East Timor', ('East Timor')),
        ('Ecuador', ('Ecuador')),
        ('Egypt', ('Egypt')),
        ('El Salvador', ('El Salvador')),
        ('Equatorial Guinea', ('Equatorial Guinea')),
        ('Eritrea', ('Eritrea')),
        ('Estonia', ('Estonia')),
        ('Ethiopia', ('Ethiopia')),
        ('Falkland Islands', ('Falkland Islands')),
        ('Faroe Islands', ('Faroe Islands')),
        ('Fiji', ('Fiji')),
        ('Finland', ('Finland')),
        ('France', ('France')),
        ('French Guiana', ('French Guiana')),
        ('French Polynesia', ('French Polynesia')),
        ('French Southern Ter', ('French Southern Ter')),
        ('Gabon', ('Gabon')),
        ('Gambia', ('Gambia')),
        ('Georgia', ('Georgia')),
        ('Germany', ('Germany')),
        ('Ghana', ('Ghana')),
        ('Gibraltar', ('Gibraltar')),
        ('Great Britain', ('Great Britain')),
        ('Greece', ('Greece')),
        ('Greenland', ('Greenland')),
        ('Grenada', ('Grenada')),
        ('Guadeloupe', ('Guadeloupe')),
        ('Guam', ('Guam')),
        ('Guatemala', ('Guatemala')),
        ('Guinea', ('Guinea')),
        ('Guyana', ('Guyana')),
        ('Haiti', ('Haiti')),
        ('Hawaii', ('Hawaii')),
        ('Honduras', ('Honduras')),
        ('Hong Kong', ('Hong Kong')),
        ('Hungary', ('Hungary')),
        ('Iceland', ('Iceland')),
        ('Indonesia', ('Indonesia')),
        ('India', ('India')),
        ('Iran', ('Iran')),
        ('Iraq', ('Iraq')),
        ('Ireland', ('Ireland')),
        ('Isle of Man', ('Isle of Man')),
        ('Israel', ('Israel')),
        ('Italy', ('Italy')),
        ('Jamaica', ('Jamaica')),
        ('Japan', ('Japan')),
        ('Jordan', ('Jordan')),
        ('Kazakhstan', ('Kazakhstan')),
        ('Kenya', ('Kenya')),
        ('Kiribati', ('Kiribati')),
        ('Korea North', ('Korea North')),
        ('Korea Sout', ('Korea South')),
        ('Kuwait', ('Kuwait')),
        ('Kyrgyzstan', ('Kyrgyzstan')),
        ('Laos', ('Laos')),
        ('Latvia', ('Latvia')),
        ('Lebanon', ('Lebanon')),
        ('Lesotho', ('Lesotho')),
        ('Liberia', ('Liberia')),
        ('Libya', ('Libya')),
        ('Liechtenstein', ('Liechtenstein')),
        ('Lithuania', ('Lithuania')),
        ('Luxembourg', ('Luxembourg')),
        ('Macau', ('Macau')),
        ('Macedonia', ('Macedonia')),
        ('Madagascar', ('Madagascar')),
        ('Malaysia', ('Malaysia')),
        ('Malawi', ('Malawi')),
        ('Maldives', ('Maldives')),
        ('Mali', ('Mali')),
        ('Malta', ('Malta')),
        ('Marshall Islands', ('Marshall Islands')),
        ('Martinique', ('Martinique')),
        ('Mauritania', ('Mauritania')),
        ('Mauritius', ('Mauritius')),
        ('Mayotte', ('Mayotte')),
        ('Mexico', ('Mexico')),
        ('Midway Islands', ('Midway Islands')),
        ('Moldova', ('Moldova')),
        ('Monaco', ('Monaco')),
        ('Mongolia', ('Mongolia')),
        ('Montserrat', ('Montserrat')),
        ('Morocco', ('Morocco')),
        ('Mozambique', ('Mozambique')),
        ('Myanmar', ('Myanmar')),
        ('Nambia', ('Nambia')),
        ('Nauru', ('Nauru')),
        ('Nepal', ('Nepal')),
        ('Netherland Antilles', ('Netherland Antilles')),
        ('Netherlands', ('Netherlands (Holland, Europe)')),
        ('Nevis', ('Nevis')),
        ('New Caledonia', ('New Caledonia')),
        ('New Zealand', ('New Zealand')),
        ('Nicaragua', ('Nicaragua')),
        ('Niger', ('Niger')),
        ('Nigeria', ('Nigeria')),
        ('Niue', ('Niue')),
        ('Norfolk Island', ('Norfolk Island')),
        ('Norway', ('Norway')),
        ('Oman', ('Oman')),
        ('Pakistan', ('Pakistan')),
        ('Palau Island', ('Palau Island')),
        ('Palestine', ('Palestine')),
        ('Panama', ('Panama')),
        ('Papua New Guinea', ('Papua New Guinea')),
        ('Paraguay', ('Paraguay')),
        ('Peru', ('Peru')),
        ('Phillipines', ('Philippines')),
        ('Pitcairn Island', ('Pitcairn Island')),
        ('Poland', ('Poland')),
        ('Portugal', ('Portugal')),
        ('Puerto Rico', ('Puerto Rico')),
        ('Qatar', ('Qatar')),
        ('Republic of Montenegro', ('Republic of Montenegro')),
        ('Republic of Serbia', ('Republic of Serbia')),
        ('Reunion', ('Reunion')),
        ('Romania', ('Romania')),
        ('Russia', ('Russia')),
        ('Rwanda', ('Rwanda')),
        ('St Barthelemy', ('St Barthelemy')),
        ('St Eustatius', ('St Eustatius')),
        ('St Helena', ('St Helena')),
        ('St Kitts-Nevis', ('St Kitts-Nevis')),
        ('St Lucia', ('St Lucia')),
        ('St Maarten', ('St Maarten')),
        ('St Pierre & Miquelon', ('St Pierre & Miquelon')),
        ('St Vincent & Grenadines', ('St Vincent & Grenadines')),
        ('Saipan', ('Saipan')),
        ('Samoa', ('Samoa')),
        ('Samoa American', ('Samoa American')),
        ('San Marino', ('San Marino')),
        ('Sao Tome & Principe', ('Sao Tome & Principe')),
        ('Saudi Arabia', ('Saudi Arabia')),
        ('Senegal', ('Senegal')),
        ('Seychelles', ('Seychelles')),
        ('Sierra Leone', ('Sierra Leone')),
        ('Singapore', ('Singapore')),
        ('Slovakia', ('Slovakia')),
        ('Slovenia', ('Slovenia')),
        ('Solomon Islands', ('Solomon Islands')),
        ('Somalia', ('Somalia')),
        ('South Africa', ('South Africa')),
        ('Spain', ('Spain')),
        ('Sri Lanka', ('Sri Lanka')),
        ('Sudan', ('Sudan')),
        ('Suriname', ('Suriname')),
        ('Swaziland', ('Swaziland')),
        ('Sweden', ('Sweden')),
        ('Switzerland', ('Switzerland')),
        ('Syria', ('Syria')),
        ('Tahiti', ('Tahiti')),
        ('Taiwan', ('Taiwan')),
        ('Tajikistan', ('Tajikistan')),
        ('Tanzania', ('Tanzania')),
        ('Thailand', ('Thailand')),
        ('Togo', ('Togo')),
        ('Tokelau', ('Tokelau')),
        ('Tonga', ('Tonga')),
        ('Trinidad & Tobago', ('Trinidad & Tobago')),
        ('Tunisia', ('Tunisia')),
        ('Turkey', ('Turkey')),
        ('Turkmenistan', ('Turkmenistan')),
        ('Turks & Caicos Is', ('Turks & Caicos Is')),
        ('Tuvalu', ('Tuvalu')),
        ('Uganda', ('Uganda')),
        ('United Kingdom', ('United Kingdom')),
        ('Ukraine', ('Ukraine')),
        ('United Arab Erimates', ('United Arab Emirates')),
        ('United States of America', ('United States of America')),
        ('Uraguay', ('Uruguay')),
        ('Uzbekistan', ('Uzbekistan')),
        ('Vanuatu', ('Vanuatu')),
        ('Vatican City State', ('Vatican City State')),
        ('Venezuela', ('Venezuela')),
        ('Vietnam', ('Vietnam')),
        ('Virgin Islands (Brit)', ('Virgin Islands (Brit)')),
        ('Virgin Islands (USA)', ('Virgin Islands (USA)')),
        ('Wake Island', ('Wake Island')),
        ('Wallis & Futana Is', ('Wallis & Futana Is')),
        ('Yemen', ('Yemen')),
        ('Zaire', ('Zaire')),
        ('Zambia', ('Zambia')),
        ('Zimbabwe', ('Zimbabwe'))
    ], render_kw={"placeholder": "Choose Country"})
    website_link = URLField(label = 'Website Link',validators=[DataRequired(), Length(min=6, max=500,  message='⚠️ URL length must be between %(min)d and %(max)d characters!')], render_kw={"placeholder": "Website Link"})
    github_link = URLField(label = 'GitHub Link',validators=[DataRequired(), Length(min=6, max=500,  message='⚠️ URL length must be between %(min)d and %(max)d characters!')], render_kw={"placeholder": "GitHub Link"})
    twitter_link = URLField(label = 'Twitter Link',validators=[DataRequired(), Length(min=6, max=500,  message='⚠️ URL length must be between %(min)d and %(max)d characters!')], render_kw={"placeholder": "Twitter Link"})
    linkedin_link = URLField(label = 'LinkedIn Link',validators=[DataRequired(), Length(min=6, max=500,  message='⚠️ URL length must be between %(min)d and %(max)d characters!')], render_kw={"placeholder": "LinkdIn Link"})
    facebook_link = URLField(label = 'Facebook Link',validators=[DataRequired(), Length(min=6, max=500,  message='⚠️ URL length must be between %(min)d and %(max)d characters!')], render_kw={"placeholder": "Facebook Link"})
    codewars_link = URLField(label = 'CodeWars Link',validators=[DataRequired(), Length(min=6, max=500,  message='⚠️ URL length must be between %(min)d and %(max)d characters!')], render_kw={"placeholder": "CodeWars Link"})
    submit = SubmitField(label=('Submit'))